server:
  port: 8766
spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    ip-address: 127.0.0.1:8766
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
#    ip-address: 120.78.88.169:8766
  client:
    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
      defaultZone: http://120.78.88.169:8761/eureka/,http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

