eureka:
  client:
    service-url:
      defaultZone: http://120.78.88.169:8762/eureka
server:
  port: 9001
file:
  staticAccessPath: /static/head/**
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  uploadFolder: d://uploadFiles/
imgBasePath: http://localhost:9001/static/head
spring:
  application:
    name: image-service
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000
  zipkin:
    base-url: http://127.0.0.1:9411/
    locator:
      discovery:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080

security:
  oauth2:
    resource:
      id: user-service
      user-info-uri: http://localhost:8763/auth/user
      prefer-token-info: false