eureka:
  instance:
    ip-address: http://localhost:8000
  client:
    service-url:
      #      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
      defaultZone: http://120.78.88.169:8762/eureka/

spring:
  application:
    name: email-service
  mail:
    username: HuangChiXin6@163.com
    password: 19971030Hcx
    host: smtp.163.com
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
    port: 25
    default-encoding: UTF-8
  redis:
    database: 0
    host: 120.78.88.169
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  zipkin:
    base-url: http://47.112.188.28:9411/
    locator:
      discovery:
        enabled: true
  boot:
    admin:
      client:
        url: http://120.78.88.169:8080

security:
  oauth2:
    resource:
      id: user-service
      user-info-uri: http://localhost:8763/auth/user
      prefer-token-info: false
server:
  port: 8000